### ISSUE TITLE
Cannot find module 'ng2-sweetalert2'

### ISSUE THREAD

**Issue by kriminal666** [seiyria/ng2-sweetalert2#1] opened 2016-06-04 19:00 UTC
Hi.. I'm new with all this, trying to use sweet alert with angular2-quickstart example of heroes..
I have executed npm install -s anda package is added to my node_modules folder. I created new component in my app folder where i'm trying to import the module.. I have added it to my systemjs.config.js.. 3 days trying different things and always the same error when running npm start.. 
Cannot find module 'ng2-sweetalert2'..

Can you tell my the way to import the module???
Here my systemjs.config

``` javascript
(function(global) {


  // map tells the System loader where to look for things

  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'ng2-sweetalert2':            'node_modules/ng2-sweetalert2'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'ng2-sweetalert2':            { defaultExtension: 'js' }

  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Add package entries for angular packages
  ngPackageNames.forEach(function(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  });
  var config = {
    map: map,
    packages: packages
  }
  System.config(config);
})(this);

```

Her my tsconfig.json:

```

  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```

And my new component:

```
import { SweetAlertService } from 'ng2-sweetalert2';
import { Component } from '@angular/core';
import {Injectable} from '@angular/core';


@Component({
  providers: [SweetAlertService]
})

@Injectable()
export class SweetAlert {

  swalService : SweetAlertService;

  static get parameters() {
    return [[SweetAlertService]];
  }

  constructor(swal) {
    this.swalService = swal;
  }
}
```

Thanks..

**Comment by seiyria** [comment] 2016-06-04 19:03
I have no idea. I've never used systemjs.

**Comment by kriminal666** [comment] 2016-06-04 19:05
Ok.. Thanks for your answer..

**Comment by masiamj** [comment] 2016-07-28 16:31
Is there any way we can get an example of how to use this with SystemJS? Maybe someone from the community? Thanks!

**Comment by fergalmoran** [comment] 2016-07-29 20:48
Same issue with webpack.

**Comment by seiyria** [comment] 2016-07-29 20:54
It works fine with webpack - that's what I use.

**Comment by fergalmoran** [comment] 2016-08-02 11:19
I'm getting exactly the same issue as the OP with webpack.
Could you show me your vendor imports (I think this may be where the issue is)?

**Comment by seiyria** [comment] 2016-08-02 12:14
https://github.com/IdleLands/Play here is a project where I'm using this lib.

**Comment by Kabangi** [comment] 2016-08-05 08:09
Save issue with webpack.

The issue goes away when you do something like `import  'ng2-sweetalert2';`

**Comment by seiyria** [comment] 2016-08-05 10:25
@kabangi it's not magic, you have to import it somewhere. Normally you'd import and bootstrap the service, but really, do you expect it to just know you installed it?

**Comment by Kabangi** [comment] 2016-08-05 10:41
@seiyria Sure you have to install and bootstrap. What I meant by my comment above is that, when you do the import using this syntax `import { SweetAlertService } from 'ng2-sweetalert2';` You get this bug `Cannot find module 'ng2-sweetalert2'..` but when you do the import using this syntax `import 'ng2-sweetalert2'` the error goes away.

**Comment by seiyria** [comment] 2016-08-05 10:53
Okay, so again, I use webpack and it works for me. Just saying "this issue happens on webpack" is completely unhelpful because I have demonstrated in one project above (and one other project that uses a similar config, but is not listed here) that it does work.

**Comment by fergalmoran** [comment] 2016-08-05 19:48
Using `import 'ng2-sweetalert2'` makes it work. Thanks @Kabangi

**Comment by aneesazam** [comment] 2016-08-24 15:09
Kabangi, Seiyria, fergalmoran, can you please type the complete code of component?

**Comment by Xamlware** [comment] 2016-08-28 10:50
I would like to know how to make this work with systemjs also.

**Comment by readme42** [comment] 2016-09-02 15:12
I'm sorry, but i can confirm that 

`import { SweetAlertService } from "ng2-sweetalert2";`

results in 

`Cannot find module 'ng2-sweetalert2'`.

Using the way 

`import "ng2-sweetalert2";`

won't work in my case, because i need to use `downgradeNg2Provider()` from the angular2 `UpgradeAdapter`.

**Comment by Only1MrAnderson** [comment] 2016-09-27 13:02
@seiyria  Do you have any plans to support this project and upgrade it to Angular2 Final? The reason people are having issues is you are targeting RC4 and ever since RC5 Angular2 has switched to Modules. Classes were deprecated and removed in RC6 or so.

**Comment by seiyria** [comment] 2016-09-27 13:03
@AAAnderson7301 I'd accept a PR for it but I'm not explicitly interested in migrating to final at this time. Especially because I disagree with the move to NgModule.

**Comment by joshterrill** [comment] 2016-10-04 03:52
@seiyria Since you won't do it, I will. I created a solution that works with `angular-cli` projects. I'm sure you can get it to work pretty easily with webpack or systemjs. Here's my repo: https://github.com/joshterrill/ng2-cli-sweetalert2

The only thing you have to do to make it work is make sure the `sweetalert2.min.js` and `sweetalert2.min.css` are built into your project at runtime. I don't know this works with webpack, but in `angular-cli`, all you do is add 

```

"styles": [
        "../node_modules/sweetalert2/dist/sweetalert2.min.css"
      ],
      "scripts": [
        "../node_modules/sweetalert2/dist/sweetalert2.min.js"
      ],
```

I made a README explaining how to do the rest.

**Comment by joshterrill** [comment] 2016-10-04 03:53
@AAAnderson7301 let me know if that works for you.

**Comment by Fresh-Dev-zunairzakir** [comment] 2016-10-04 11:59
Hi Gyiz, I am fresh in github and I am facing same facing an issue regarding adding "ng2-typeahead' module. 
I have added "ng2-typeahead' through npm and its properly added in my node_modules folder but when I do :

import { Typeahead } from 'ng2-typeahead';
Error: Can't find module "ng2-typeahead'.

Can any body guide me in this? Thanks.

**Comment by seiyria** [comment] 2016-10-04 12:02
This is not at all related to type ahead. Go ask on their issue tracker.

**Comment by juracy** [comment] 2016-10-06 02:10
I had had the same problem, I've just made a typescript version, flatting directories. 

I don't think that's the best approach, I've just don't know yet how to fix it here...

Here it is: https://github.com/juracy/ng2-sweetalert2

**Comment by trevorfrese** [comment] 2016-10-06 23:09
can anyone explain how they got it to work just using
`import 'ng2-sweetalert2';`
?

**Comment by joshterrill** [comment] 2016-10-07 00:06
@trevorfrese It depends on what version of angular you're using, if you're using angular-cli, systemjs, or webpack. Which of those are you using?

**Comment by trevorfrese** [comment] 2016-10-07 06:43
@joshterrill I'm using webpack :)

**Comment by joshterrill** [comment] 2016-10-07 07:04
You might have better luck with this library then: https://github.com/joshterrill/ng2-cli-sweetalert2 I know angular-cli isn't exactly the same as webpack, but it uses webpack. There should be a way that you can define styles and scripts to be bundled together at runtime and put in your index.html (in the setup section of the README I show how to do this with angular-cli, not sure if it's the same in webpacks config file. I'm sure it's similar.) and then you can use it just by importing it at the top of a component, including it in the provider, and then defining it at the top of the component, and in the constructor. Then you can use any of the methods on `swal`. (see the README for specific code examples, the version of angular-cli that I use is using webpack, so the code examples should work just by copying and pasting.) If you have any questions, open an issue on that repo. I don't want to crowd up this guys repo.

**Comment by hoxxep** [comment] 2016-10-28 15:26
I used the TypeScript library from @juracy, but had to manually add `../../node_modules/sweetalert2/dist/sweetalert2.min.css` into the `styleUrls` of my app component.

**Comment by vishal41190** [comment] 2016-11-01 18:19
+1

**Comment by crebuh** [comment] 2016-11-02 16:31
I'm also using webpack and tried 

```
  import { SweetAlertService } from "ng2-sweetalert2";
```

and

```
  import 'ng2-sweetalert2';
```

as well as the modified repository from @juracy 

In every case I get (18,35): error TS2307: Cannot find module 'ng2-sweetalert2'.

**Comment by seiyria** [comment] 2016-11-02 16:37
@crebuh here is a webpack config that I use this project in, and it works: https://github.com/IdleLands/Play/blob/master/webpack.config.js

**Comment by crebuh** [comment] 2016-11-02 17:45
@seiyria 

thx for sharing the webpack config, but I dont see anything related to sweetalert and how to make it work, here is a gist of the config is use. I'm working on an angular universal project.

https://gist.github.com/crebuh/a38bd1e2f33a1c0c95667ddde90fc6fc

**Comment by seiyria** [comment] 2016-11-02 17:58
@crebuh I just do the same thing - `import { SweetAlertService } from 'ng2-sweetalert2`. I was posting my config in the possibility that I have a loader or something that makes it work correctly. Additionally, I don't use typescript and some folks in this thread do, so that might also be a problem to look into.

**Comment by acSpock** [comment] 2016-12-07 19:14
+1 any update on getting this to work with ngModule?

**Comment by seiyria** [comment] 2016-12-07 19:55
No. If you would like to submit a pull request, feel free, but I have not made any changes.

**Comment by born2net** [comment] 2016-12-09 19:35
any plans to support angular-cli?

**Comment by seiyria** [comment] 2016-12-09 19:38
No. If you would like to submit a pull request, feel free.

**Comment by born2net** [comment] 2016-12-09 19:46
I ended switching over to a fork: https://github.com/joshterrill/ng2-cli-sweetalert2
works awesome!!!
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by hiralshah** [comment] 2016-12-21 06:45
`import {SweetAlertService} from "ng2-sweetalert2";`

is not working with my code, hence I wrote following:

`import "ng2-sweetalert2";`

This is not throwing error but now how do I use SweetAlertService to access swal?

Please help

**Comment by beeman** [comment] 2016-12-27 08:14
Hey all, 

fyi sweetalert2 just got upgraded and can now be used in TypeScript straight away by importing and using it.  

I've completely moved away from any angular-sweetalert abstractions and just written my own few methods to wrap around `swal()` directly. Works like a charm!

More info here https://github.com/limonte/sweetalert2/pull/381 .

**Comment by nareshcharykotha** [comment] 2016-12-28 05:59
hey all,
in my case this is working..i used this url 
http://plnkr.co/edit/3WS18o7baXN1uegyuJCc?p=preview

**Comment by ghost** [comment] 2016-12-30 13:24
@nareshcharykotha: Thanks for this suggestion. Easiest this far yet so simple when using SystemJS :)

**Comment by acSpock** [comment] 2017-01-03 18:24
@beeman Thanks for the link. Do you have an example of using this with webpack? I tried importing the latest sweetalert as described by toverux but am getting 'sweetalert2_1.default is not a function' when executing swal in my component.

What's the correct way to import this in app.module? and is there any special configuration in webpack we need to adjust to get this working?

Cheers

**Comment by beeman** [comment] 2017-01-03 18:55
@acSpock I've created a repo with a simple demo of the functionality: https://github.com/beeman/angular-cli-sweetalert2-demo . You can see it working here: https://beeman.github.io/angular-cli-sweetalert2-demo

As you can see in the second commit there is no special configuration needed. Just `npm install --save sweetalert2` and to use the installed module I created a service that imports from `sweetalert2`. 

I then load this service in my component and call into the `alert()` method I created.

**Comment by acSpock** [comment] 2017-01-03 19:27
Thanks for the reply beeman. I think my typings is not configured correctly to support the latest sweetalert. I need to investigate further.

**Comment by NoMercy235** [comment] 2017-01-11 15:25
Hello!

@acSpock, have you managed to find a solution to the problem? I'm also stuck on the 'sweetalert2_1.default is not a function' problem. The only difference between my project and @beeman is that I use webpack, and haven't used angular-cli to make the project. But I doubt that has any influence.

This is what I did:
- in AppModule
`import { SweetAlert } from 'app/shared/sweet-alert.service';

@NgModule({
   /* code */
   providers: [ SweetAlert ]
})
export class AppModule { /* code */}`



- in SweetAlert, everything is similar to the AlertService from @beeman 's project:
`
import { Injectable } from '@angular/core';
import swal, { SweetAlertOptions } from 'sweetalert2';

@Injectable()
export class SweetAlert {

    alert(title, text, type) {
        const options: SweetAlertOptions = {
            type,
            title,
            text,
        };

        console.log(swal);
        return swal(options);
    }
}
`
- somewhere in the app:
this._alertService.alert("test", "test", "success");

Also, the console.log(swal) shows undefined.

**Comment by toverux** [comment] 2017-01-13 18:24
@NoMercy235 I'm the person who's responsible of SweetAlert's compatibility with TypeScript. The issue have been fixed in a recent version of SweetAlert2, so please update it! :) That issue occurs in 99% of the cases with Webpack 1 users or Webpack 2 users that don't use ES 2015 exports in their tsconfig.json.

**Comment by NoMercy235** [comment] 2017-01-13 22:25
Hello @toverux ! I've managed to get it working eventually. I think I've forgotten to include the css file.
Once I added this:
@import '~sweetalert2/src/sweetalert2.scss';
It worked after a few more changes. I was on version 6.2.9 and it was still giving me errors, but after updating to 6.3.1, everything worked perfectly fine. Thank you for your work! 👍

**Comment by toverux** [comment] 2017-01-13 22:45
Absolutely, you need to import the CSS! Using an ES 2015 `import` for a CSS file, is, in fact, very specific to webpack, that's why we haven't documented this in the readme. Maybe we should make the usage instructions a bit clearer about this. So, thank you too!

**Comment by aelbatal** [comment] 2017-01-15 12:34
For me, I found no need to install this package. I just installed the original npm package `npm install sweetalert2 --save` then I imported the needed files in my custom service class
```
import 'sweetalert2/dist/sweetalert2.min.js';
import 'sweetalert2/dist/sweetalert2.min.css';
import { default as swal } from 'sweetalert2';
```
reference: [https://limonte.github.io/sweetalert2/](https://limonte.github.io/sweetalert2/)

**Comment by toverux** [comment] 2017-01-19 12:52
As this package stays inactive and lost part of its utility since SweetAlert2 exports its type definitions, I wanted to let you know about my new project : https://github.com/toverux/ngsweetalert2
It's not a wrapper like this project but intends to provide a true Angular integration, for example, by providing a Swal directive.

**Comment by seiyria** [comment] 2017-01-19 14:38
Inactive is a bit of a stretch. It fits the use-case I designed it for, and the fact that other people get it working (probably a few hundred people) is nice. The fact that it inspired probably 5 or 10 forks is nice, too, but I wish they would have contributed back instead of just going their own way - it probably could have made something nicer overall.

**Comment by toverux** [comment] 2017-01-19 16:17
I said "inactive" because the latest commit is from Oct 2016, and the dependencies on SweetAlert and Angular are somewhat outdated. Moreover, you've explicitly stated that you're not interested to upgrade the build process (ex. to fix this issue or make the library AoT-compatible). And like beeman said, a service/wrapper around SweetAlert is not really necessary anymore, that's why I created something *different* (not a fork). I wouldn't have posted the message above if this project showed any kind of activity!

**Comment by seiyria** [comment] 2017-01-19 16:19
Yeah, and all my projects that use this are that version of angular and I guess swal could be upgraded, but it's not that big of a deal. I said several times that _I_ am not interested in doing the upgrade, but I would take a PR for it. But yes, it's probably not necessary anymore. At the time, it was.

**Comment by cantonetti-sts** [comment] 2017-01-20 16:02
@joshterrill @seiyria 

**Thank you @joshterrill! I finally made it work after a little tweak.**

In my case I was able to finally make it work following joshterrill's approach but had to do an extra step moving the index.ts file from the src directory inside the ng2-cli-sweetalert folder. Here is the step by step that made it work for me:

**Install**
`
npm install ng2-cli-sweetalert2     `              
 
**Set up** angular-cli.json
In the angular-cli.json file you'll need to add references to the sweetalert2 javascript and css files. To do this, all you need to do is
 
```
...
"styles": [
  ...
  "../node_modules/sweetalert2/dist/sweetalert2.min.css"
],
"scripts": [
  "../node_modules/sweetalert2/dist/sweetalert2.min.js"
],
...
```
 
**Move the index file:**
 
`{YOUR_PROJECT_TOP_DIRECTORY}\node_modules\ng2-cli-sweetalert2\src\index.ts`
 
To the parent directory:
 
`{YOUR_PROJECT_TOP_DIRECTORY}\node_modules\ng2-cli-sweetalert2`
 
The compiler looks inside \node_modules\ng2-cli-sweetalert2 for the index.ts file to compile it correctly. I am not sure why it doesn’t just install that way, but this was the only way that I could make it work for me.

**Use**

In the module that you want to use it in, import it using 
 
`import { SweetAlertService } from 'ng2-cli-sweetalert2';`

Then add to the providers array in the @Component definition:
 
```
@Component({
  selector: 'some-component',
  templateUrl: 'some-component.component.html',
  providers: [SweetAlertService]
})
```
 
Create a variable called swal and give it a type of SweetAlertService. Then define it in your constructor and set your variable equal to it.
 
```
swal: SweetAlertService;
constructor(private _swal: SweetAlertService) {
  this.swal = this._swal;
}
```
 
Now you can use any of the sweetalert2 methods like
 
```
this.swal.success(
  {title: 'Are you sure?',
  text: 'You will not be able to recover this imaginary file!',
  showCancelButton: true,
  confirmButtonText: 'Yes, delete it!',
  cancelButtonText: 'No, keep it'}
).then(function(success) {
  console.log("Clicked confirm");
}, function() {
  console.log("Clicked cancel");
});
 
```

**Comment by noagr1** [comment] 2017-01-25 11:28
@nareshcharykotha  I have tried your solution and it is working great but what if I need to get a test value?
How do I access the result in my angular2?
 ```
swal({
            title: 'Please enter the new cycle name',
            input: 'text',
            showCancelButton: true,
            inputValidator: function (value) {
                return new Promise(function (resolve, reject) {
                if (value) {
                    resolve()
                } else {
                    reject('You need to write something!')
                }
            })
            }
         }).then(function (result) {
            //Here I want to move the result to my component and don't know how.
         })
```

**Comment by seiyria** [comment] 2017-01-25 13:47
This issue has far overstretched it's purpose. It is not a help line for basic swal implementations or help with other peoples forks. If you are having issues with either of those, please go to those repositories instead of posting in this issue.

**Closed as completed by seiyria** 2017-01-25 13:47 UTC
